# Generated by Django 5.1.2 on 2024-10-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta_pago',
            name='liquido_recibir',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
