# Generated by Django 5.1.2 on 2024-10-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_boleta_pago_liquido_recibir'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='dui',
            field=models.CharField(default=5328681, max_length=10),
            preserve_default=False,
        ),
    ]
