# Generated by Django 5.1.2 on 2024-10-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0005_alter_empleados_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.cargo'),
        ),
    ]
