# Generated by Django 5.1.2 on 2024-10-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0006_alter_empleados_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.CharField(max_length=50),
        ),
    ]
